[package]
name = "term3d"
version = "0.1.0"
authors = ["d86leader <d86leader@mail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
ctrlc = "3.1.3"
rand = "0.7.2"
